services:
  vote:
    container_name: vote
    image: roxsross12/voting-app:vote-1.0.0
    depends_on:
      - redis
      
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    container_name: result
    image: roxsross12/voting-app:result-1.0.0
    depends_on:
      - database
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: roxsross12/voting-app:worker-1.0.0
    depends_on:
       - redis
       - database
    networks:
      - back-tier

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    volumes:
      - "redis-data:/data"
    networks:
      - back-tier

  database:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
  
    networks:
      - back-tier

volumes:
  db-data:
  redis-data:

networks:
  front-tier:
  back-tier:
